dist: xenial

language: ruby
before_install:
- gem update --system
- gem install bundler
cache: bundler
env:
  global:
  - JEKYLL_ENV=production
script: bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: EBY2ItB/VghAohv2NRLBZS8JV4W5dF0haCP4t+dmonSKvo/8B3/+DEAOgc02rR3dtKeg5tyuilvnd6YuMp9wpttfcnpudBakQqBzRDBqaunDG389Kvu4xaGHZ8bO0vrIuhJqkBsx5IVDaUYIyvpwysnoYweJGiSnHVRbtNm8XQRh6JrfhqbIsF9ToKVgilZe5N+D6j8lZiccosaWTGpeVM6pmMyAUVy59vXF+p/EPpVmKp+BoYpGz37B5Rp3QwQWz8WUCxJN3KA9ZCinmalffeRBijwLudA0mRnu/8q7JpVzp2KaQpYP5j1kaTXnu6RbMAspPyz0KFLVt/H1hSFuYipSlChWgvm18lnpEvjgpgsGYPN65USbQCOo3NBT5ihSk4Q+UKeu/Lv8SM5rdtgmp5Iz8Z9xIrWI/bkp7N5ut42814KxuqMmEbPJvwdPMzPFXfzY5yLL4nKx1Eozb42i3PMHTvpBZgZLcu49YCnP117oqnzYF1S8K26soO2oQm0aBkZmQaZhumCvMODQD+RWfmEcUCiZLc4f5qTYd6pgr5Uj7pG3ExAFh7XMtp7pKPamYt+Ud6vr2J6vTSnn8gHUNHygMcoQ/N1wWtYBsiFI2l8HER0VZwVvAIpS7zFLQ7dgMcgaoHIkaK+TCwv9261JcsFuDv12b50RFHgRrU7uoI0=
