title: Jon’s Notes
baseurl: ""
url: "https://notes.jjc1138.net/"
twitter_username: JJC1138

markdown: kramdown
theme: minima
minima:
  date_format: "%F"
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
