name: Build and Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Update RubyGems
      run: gem update --system --no-document
    - name: Install Bundler
      run: gem install bundler --no-document
    - name: Bundled gem caching
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: _site
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build
          path: _site
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.3.0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
         args: deploy --only hosting
